My profile markup
pavelkortp/social-network pull request #1
Opened 2024-03-23 20:50 UTC by pavelkortp

2024-03-24 14:38 UTC, hryhorii11 requested changes

2024-03-24 14:38 UTC, hryhorii11 commented on app/build.gradle.kts
> +    implementation("com.github.bumptech.glide:glide:4.16.0")
versions should be expoted to variable

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/java/com/pavelkortp/socialnetwork/AuthActivity.kt
> +    private lateinit var binding: ActivityAuthBinding
I recommend using lazy initialization for binding

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/java/com/pavelkortp/socialnetwork/AuthActivity.kt
> +        editor.putString("email",email)
export preferences key to constant

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/java/com/pavelkortp/socialnetwork/AuthActivity.kt
> +            binding.PasswordInput.error = "Password is empty"
export to string resource

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/java/com/pavelkortp/socialnetwork/AuthActivity.kt
> +            binding.EmailInput.error = "Email is empty"
also export to string resource

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/java/com/pavelkortp/socialnetwork/AuthActivity.kt
> +            putExtra("password", password)
why are you passing the password in the MainActivity?

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/java/com/pavelkortp/socialnetwork/LoginActivity.kt
it seems to me that you should not implement loginActivity for first level

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/java/com/pavelkortp/socialnetwork/LoginActivity.kt
> +        binding.LoginBTN.setOnClickListener {
i recommend create method for setting listeners to decompose onCreate method

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/java/com/pavelkortp/socialnetwork/LoginActivity.kt
> +        if (email.isBlank()) {
this code is repeated in the activity, maybe it makes sense to create a class for validation

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/java/com/pavelkortp/socialnetwork/MainActivity.kt
> +    class State(var counter: Int) : Parcelable
export class to another file

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/res/drawable-mdpi/bob.gif
)

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/res/layout/activity_auth.xml
> +    <EditText
use textInputLayout instead of editText

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/res/layout/activity_auth.xml
> +        android:textSize="24sp"
all sp or dp values shoulde be exported to dimens

2024-03-24 14:38 UTC, hryhorii11 commented on app/src/main/res/layout/activity_login.xml
> +        android:text="Email"
export all text to string resources

2024-03-26 23:10 UTC, pavelkortp commented on app/build.gradle.kts
> +    implementation("com.github.bumptech.glide:glide:4.16.0")
Only glide? Or should others also be included in separate variables?

2024-03-26 23:14 UTC, pavelkortp commented on app/src/main/java/com/pavelkortp/socialnetwork/AuthActivity.kt
> +    private lateinit var binding: ActivityAuthBinding
What`s the benefit of this approach?

2024-04-11 08:44 UTC, merged